lang: en
title: openSUSE Download
title_short: Download
description: |
  The openSUSE Download repositories providing all of the software in
  the openSUSE distributions and openSUSE Build Service repositories
email: admin@opensuse.org
copyright: '&copy; 2015-2020 SUSE LLC., openSUSE contributors'
baseurl: ""
url: "http://download.opensuse.org"

navbar_links:
   -
     text: Shortcuts
     children:
       -
         link: /debug/
         text: debug
       -
         link: /distribution/
         text: distribution
       -
         link: /factory/
         text: factory
       -
         link: /ports/
         text: ports
       -
         link: /repositories/
         text: repositories
       -
         link: /source/
         text: source
       -
         link: /tumbleweed/
         text: tumbleweed
       -
         link: /update/
         text: update

footer_links:
  -
    text: Source Code
    link: https://github.com/openSUSE/mirrorbrain
  -
    text: Report Bugs
    link: https://bugzilla.opensuse.org/
  -
    text: Imprint
    link: https://en.opensuse.org/Imprint

theme: jekyll-theme-opensuse

exclude: [README.md, Gemfile, Gemfile.lock, vendor, LICENSE]
